from fastapi import APIRouter, Depends, HTTPException
from motor.motor_asyncio import AsyncIOMotorDatabase
from app.core.database import get_database
from app.api.dependencies import get_current_user
from app.services.gemini_service import generate_meal_plan
from app.services.auth_service import get_user_metrics
from app.schemas.workout_plan import DietPreferences, MealPlan
from bson import ObjectId
from datetime import datetime
import logging

router = APIRouter()
logger = logging.getLogger(__name__)

@router.post("/generate", response_model=dict)
async def generate_meal_plan_endpoint(
    preferences: DietPreferences,
    db: AsyncIOMotorDatabase = Depends(get_database),
    current_user: dict = Depends(get_current_user)
):
    """
    Generate a personalized meal plan using AI based on user preferences.

    - Fetches user data from database
    - Calls Gemini AI service for meal plan generation
    - Stores the meal plan in MongoDB
    - Returns the generated meal plan
    """
    try:
        # Get user metrics
        user_metrics = await get_user_metrics(current_user)
        if not user_metrics:
            raise HTTPException(status_code=400, detail="User metrics not found. Please complete your profile.")

        # Get stored food preferences from the database
        from app.services.auth_service import get_user_food_preferences
        food_prefs_doc = await get_user_food_preferences(current_user)
        if food_prefs_doc:
            db_food_preference = food_prefs_doc.get("food_preference", "veg")
            db_allergies = food_prefs_doc.get("allergies", [])
            db_daily_foods = food_prefs_doc.get("daily_foods", [])
        else:
            db_food_preference = "veg"
            db_allergies = []
            db_daily_foods = []

        # Prepare user data for AI service
        user_data = {
            "age": user_metrics.get("age", 25),
            "gender": user_metrics.get("gender", "Male"),
            "height": user_metrics.get("height", 170),
            "weight": user_metrics.get("weight", 70),
            "bmi": user_metrics.get("bmi", 22.5),
            "goal": user_metrics.get("goal", "General Fitness"),
            "calories_goal": user_metrics.get("calories_goal"),
            "activity_level": user_metrics.get("activity_level", "Moderately Active")
        }

        # Convert preferences to dict for AI service (prioritize global db settings over request payload)
        preferences_dict = {
            "food_preference": db_food_preference,
            "allergies": db_allergies,
            "daily_foods": db_daily_foods,
            "meals_per_day": preferences.meals_per_day
        }

        # Generate meal plan using AI
        logger.info(f"Generating meal plan for user: {current_user.username}")
        meal_plan = await generate_meal_plan(user_data, preferences_dict)

        # Validate the generated meal plan
        if not meal_plan or "meals" not in meal_plan:
            logger.error("Invalid meal plan generated by AI service")
            raise HTTPException(status_code=500, detail="Failed to generate valid meal plan")

        # Prepare meal plan document for storage
        meal_plan_doc = {
            "user_id": current_user.username,
            "meal_plan": meal_plan,
            "preferences": preferences_dict,
            "created_at": datetime.utcnow()
        }

        # Store in MongoDB
        result = await db.user_meal_plans.insert_one(meal_plan_doc)
        logger.info(f"Stored meal plan with ID: {result.inserted_id}")

        # Return the meal plan with ID
        return {
            "id": str(result.inserted_id),
            "meal_plan": meal_plan,
            "preferences": preferences_dict,
            "created_at": meal_plan_doc["created_at"]
        }

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error generating meal plan: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to generate meal plan")

@router.get("/supplements", response_model=dict)
async def get_supplements_endpoint(
    db: AsyncIOMotorDatabase = Depends(get_database),
    current_user: dict = Depends(get_current_user)
):
    """
    Get personalized supplement suggestions using AI with state-aware caching.
    """
    try:
        # Get current user parameters
        user_metrics = await get_user_metrics(current_user)
        if not user_metrics:
            raise HTTPException(status_code=400, detail="User metrics not found. Please complete your profile.")
        
        current_goals = user_metrics.get("goals", [user_metrics.get("goal")])
        current_level = user_metrics.get("gym_level", "Beginner")

        # Check for cached stack
        cached_stack = await db.user_supplements.find_one({"user_id": current_user.username})
        
        if cached_stack:
            # Stale Check: Only re-generate if goals or gym_level has changed
            cached_goals = cached_stack.get("cached_goals", [])
            cached_level = cached_stack.get("cached_level", "Beginner")
            
            if set(current_goals) == set(cached_goals) and current_level == cached_level:
                logger.info(f"Serving cached supplement stack for {current_user.username}")
                return cached_stack.get("data")

        # If not cached or stale, generate new stack
        logger.info(f"Generating NEW supplement stack for {current_user.username}")
        from app.services.gemini_service import generate_supplements
        supplements = await generate_supplements(user_metrics)
        
        # Save to database
        new_stack = {
            "user_id": current_user.username,
            "data": supplements,
            "cached_goals": current_goals,
            "cached_level": current_level,
            "updated_at": datetime.utcnow()
        }
        
        await db.user_supplements.update_one(
            {"user_id": current_user.username},
            {"$set": new_stack},
            upsert=True
        )
        
        return supplements

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error managing supplement suggestions: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to manage supplement suggestions")

from fastapi import UploadFile, File
import base64

@router.post("/analyze-report", response_model=dict)
async def analyze_report_endpoint(
    file: UploadFile = File(...),
    current_user: dict = Depends(get_current_user)
):
    """
    Analyze blood report and suggest supplements.
    """
    try:
        # Get user metrics
        user_metrics = await get_user_metrics(current_user)
        if not user_metrics:
            raise HTTPException(status_code=400, detail="User metrics not found.")
        
        # Read file data
        contents = await file.read()
        file_b64 = base64.b64encode(contents).decode('utf-8')
        
        # Analyze using Gemini
        from app.services.gemini_service import analyze_blood_report
        result = await analyze_blood_report(file_b64, file.content_type, user_metrics)
        
        # Archive the report analysis in the database
        db = get_database()
        report_doc = {
            "user_id": current_user.username,
            "analysis": result,
            "created_at": datetime.utcnow(),
            "file_type": file.content_type
        }
        await db.user_blood_reports.insert_one(report_doc)
        logger.info(f"Archived clinical report analysis for {current_user.username}")
        
        # Also sync these clinical recommendations into the active supplement stack
        if result.get("recommendations"):
            # Map report recommendations to standard supplement format
            clinical_supplements = []
            for rec in result["recommendations"]:
                clinical_supplements.append({
                    "name": rec.get("name"),
                    "dosage": rec.get("dosage"),
                    "timing": rec.get("timing"),
                    "benefit": rec.get("reason"),
                    "description": f"Clinical recommendation based on: {result.get('report_summary', 'Blood Analysis')}"
                })
            
            # Fetch existing stack or create new one
            existing_stack = await db.user_supplements.find_one({"user_id": current_user.username})
            
            if existing_stack:
                current_data = existing_stack.get("data", {"supplements": [], "report_supplements": []})
                current_data["report_supplements"] = clinical_supplements
            else:
                current_data = {
                    "supplements": [],
                    "report_supplements": clinical_supplements,
                    "safety_disclaimer": "Clinical recommendations based on blood report analysis."
                }

            await db.user_supplements.update_one(
                {"user_id": current_user.username},
                {"$set": {
                    "data": current_data,
                    "cached_goals": user_metrics.get("goals", [user_metrics.get("goal")]),
                    "cached_level": user_metrics.get("gym_level", "Beginner"),
                    "updated_at": datetime.utcnow(),
                    "has_clinical_data": True
                }},
                upsert=True
            )
            logger.info(f"Synced {len(clinical_supplements)} clinical recommendations to active supplement stack.")

        return result

    except Exception as e:
        logger.error(f"Error analyzing blood report: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to analyze report")

@router.get("/list", response_model=list)
async def get_meal_plans(
    db: AsyncIOMotorDatabase = Depends(get_database),
    current_user: dict = Depends(get_current_user)
):
    """
    Get all meal plans for the current user.
    """
    try:
        # Query meal plans sorted by creation date
        cursor = db.user_meal_plans.find(
            {"user_id": current_user.username}
        ).sort("created_at", -1)

        meal_plans = []
        async for plan in cursor:
            plan["id"] = str(plan["_id"])
            del plan["_id"]
            meal_plans.append(plan)

        return meal_plans

    except Exception as e:
        logger.error(f"Error fetching meal plans: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to fetch meal plans")

@router.get("/{plan_id}", response_model=dict)
async def get_meal_plan(
    plan_id: str,
    db: AsyncIOMotorDatabase = Depends(get_database),
    current_user: dict = Depends(get_current_user)
):
    """
    Get a specific meal plan by ID.
    """
    try:
        # Validate ObjectId
        try:
            obj_id = ObjectId(plan_id)
        except:
            raise HTTPException(status_code=400, detail="Invalid meal plan ID")

        # Query specific meal plan
        plan = await db.user_meal_plans.find_one({
            "_id": obj_id,
            "user_id": current_user.username
        })

        if not plan:
            raise HTTPException(status_code=404, detail="Meal plan not found")

        # Convert ObjectId to string
        plan["id"] = str(plan["_id"])
        del plan["_id"]

        return plan

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error fetching meal plan: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to fetch meal plan")

@router.delete("/{plan_id}")
async def delete_meal_plan(
    plan_id: str,
    db: AsyncIOMotorDatabase = Depends(get_database),
    current_user: dict = Depends(get_current_user)
):
    """
    Delete a specific meal plan by ID.
    """
    try:
        # Validate ObjectId
        try:
            obj_id = ObjectId(plan_id)
        except:
            raise HTTPException(status_code=400, detail="Invalid meal plan ID")

        # Delete the meal plan
        result = await db.user_meal_plans.delete_one({
            "_id": obj_id,
            "user_id": current_user.username
        })

        if result.deleted_count == 0:
            # We can log this but we shouldn't throw an error for idempotency.
            logger.info(f"Meal plan {plan_id} already deleted or not found.")

        return {"message": "Meal plan deleted successfully"}

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error deleting meal plan: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to delete meal plan")

